// tools/fetch-fonts.mjs — self-host the site's Google Fonts.
//
// Downloads the latin + latin-ext WOFF2 files for the families the site uses
// into public/fonts/ and writes src/styles/fonts.css with matching @font-face
// rules (font-display: block, so text is never painted in a fallback face and
// then swapped). index.html preloads the weights used above the fold.
//
//   node tools/fetch-fonts.mjs
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = path.join(ROOT, 'public', 'fonts');
const CSS_OUT = path.join(ROOT, 'src', 'styles', 'fonts.css');
const FAMILIES = 'family=Big+Shoulders+Display:wght@700;800;900&family=Instrument+Sans:ital,wght@0,400;0,500;0,600;1,400';
const SUBSETS = new Set(['latin', 'latin-ext']);
// A modern browser UA makes Google answer with WOFF2 and unicode-range subsets.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36';

const css = await (await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`, { headers: { 'User-Agent': UA } })).text();
const blocks = [...css.matchAll(/\/\* (\S+) \*\/\s*@font-face \{([^}]+)\}/g)];
if (!blocks.length) throw new Error('no @font-face blocks in the Google Fonts response');

await fs.mkdir(OUT_DIR, { recursive: true });
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
let out = `/* Self-hosted fonts — generated by tools/fetch-fonts.mjs, do not edit by hand. */\n`;
const files = [];
for (const [, subset, body] of blocks) {
  if (!SUBSETS.has(subset)) continue;
  const prop = (name) => (body.match(new RegExp(`${name}:\\s*([^;]+);`)) || [])[1]?.trim();
  const family = prop('font-family').replace(/['"]/g, '');
  const style = prop('font-style') || 'normal';
  const weight = prop('font-weight') || '400';
  const url = (body.match(/url\(([^)]+)\)/) || [])[1];
  const range = prop('unicode-range');
  if (!url) continue;
  const file = `${slug(family)}-${weight.replace(/\s+/g, '-')}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`;
  const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
  await fs.writeFile(path.join(OUT_DIR, file), bytes);
  files.push({ file, family, weight, style, subset, kb: Math.round(bytes.length / 1024) });
  out += `@font-face {\n  font-family: '${family}';\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: block;\n  src: url('/fonts/${file}') format('woff2');\n  unicode-range: ${range};\n}\n`;
}
await fs.writeFile(CSS_OUT, out);
for (const f of files) console.log(`${f.file}  ${f.kb} KB`);
console.log(`${files.length} files in public/fonts, rules in src/styles/fonts.css`);
