// The 50 states for /united-states/:state — name, postal code, the main cities we
// list on the page (largest first) and the bordering states shown as "Nearby".
// States without land borders (Alaska, Hawaii) and the ones with only one or two
// list the closest states instead, so the Nearby row is never empty.

export const stateSlug = (name = '') => String(name).toLowerCase().replace(/[^a-z]+/g, '-').replace(/^-|-$/g, '');
export const statePath = (name = '') => `/united-states/${stateSlug(name)}`;

export const STATES = [
  { name: 'Alabama', code: 'AL', cities: ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile', 'Tuscaloosa', 'Hoover', 'Auburn', 'Dothan', 'Decatur', 'Madison', 'Florence', 'Phenix City', 'Prattville', 'Vestavia Hills', 'Gadsden', 'Enterprise'], near: ['Georgia', 'Florida', 'Mississippi', 'Tennessee', 'Louisiana'] },
  { name: 'Alaska', code: 'AK', cities: ['Anchorage', 'Fairbanks', 'Juneau', 'Wasilla', 'Sitka', 'Ketchikan', 'Kenai', 'Kodiak', 'Bethel', 'Palmer', 'Homer', 'Soldotna'], near: ['Washington', 'Oregon', 'Idaho', 'Montana'] },
  { name: 'Arizona', code: 'AZ', cities: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Gilbert', 'Glendale', 'Scottsdale', 'Peoria', 'Tempe', 'Surprise', 'Yuma', 'Flagstaff', 'Goodyear', 'Avondale', 'Lake Havasu City', 'Prescott'], near: ['California', 'Nevada', 'Utah', 'New Mexico', 'Colorado'] },
  { name: 'Arkansas', code: 'AR', cities: ['Little Rock', 'Fayetteville', 'Fort Smith', 'Springdale', 'Jonesboro', 'Rogers', 'Conway', 'North Little Rock', 'Bentonville', 'Pine Bluff', 'Hot Springs', 'Benton', 'Texarkana', 'Sherwood'], near: ['Louisiana', 'Mississippi', 'Missouri', 'Oklahoma', 'Tennessee', 'Texas'] },
  { name: 'California', code: 'CA', cities: ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Long Beach', 'Oakland', 'Bakersfield', 'Anaheim', 'Santa Ana', 'Riverside', 'Stockton', 'Irvine', 'Chula Vista', 'Fremont'], near: ['Oregon', 'Nevada', 'Arizona'] },
  { name: 'Colorado', code: 'CO', cities: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood', 'Thornton', 'Arvada', 'Westminster', 'Pueblo', 'Greeley', 'Boulder', 'Longmont', 'Loveland', 'Grand Junction'], near: ['Wyoming', 'Nebraska', 'Kansas', 'Oklahoma', 'New Mexico', 'Utah'] },
  { name: 'Connecticut', code: 'CT', cities: ['Bridgeport', 'Stamford', 'New Haven', 'Hartford', 'Waterbury', 'Norwalk', 'Danbury', 'New Britain', 'Meriden', 'Bristol', 'West Haven', 'Milford', 'Middletown', 'Norwich'], near: ['New York', 'Massachusetts', 'Rhode Island'] },
  { name: 'Delaware', code: 'DE', cities: ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Smyrna', 'Milford', 'Seaford', 'Georgetown', 'Elsmere', 'New Castle', 'Lewes', 'Rehoboth Beach'], near: ['Maryland', 'Pennsylvania', 'New Jersey'] },
  { name: 'Florida', code: 'FL', cities: ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg', 'Hialeah', 'Port St. Lucie', 'Tallahassee', 'Cape Coral', 'Fort Lauderdale', 'Pembroke Pines', 'Hollywood', 'Gainesville', 'Miramar', 'Coral Springs', 'Pensacola'], near: ['Georgia', 'Alabama', 'South Carolina', 'Mississippi'] },
  { name: 'Georgia', code: 'GA', cities: ['Atlanta', 'Columbus', 'Augusta', 'Macon', 'Savannah', 'Athens', 'Sandy Springs', 'South Fulton', 'Roswell', 'Johns Creek', 'Warner Robins', 'Albany', 'Alpharetta', 'Marietta', 'Valdosta', 'Smyrna'], near: ['Florida', 'Alabama', 'Tennessee', 'North Carolina', 'South Carolina'] },
  { name: 'Hawaii', code: 'HI', cities: ['Honolulu', 'Pearl City', 'Hilo', 'Kailua', 'Waipahu', 'Kaneohe', 'Mililani', 'Kahului', 'Kihei', 'Kapolei', 'Wailuku', 'Kona'], near: ['California', 'Oregon', 'Washington', 'Alaska'] },
  { name: 'Idaho', code: 'ID', cities: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Caldwell', 'Pocatello', "Coeur d'Alene", 'Twin Falls', 'Post Falls', 'Lewiston', 'Rexburg', 'Eagle', 'Moscow', 'Kuna'], near: ['Washington', 'Oregon', 'Nevada', 'Utah', 'Wyoming', 'Montana'] },
  { name: 'Illinois', code: 'IL', cities: ['Chicago', 'Aurora', 'Naperville', 'Joliet', 'Rockford', 'Springfield', 'Elgin', 'Peoria', 'Champaign', 'Waukegan', 'Cicero', 'Bloomington', 'Arlington Heights', 'Evanston', 'Schaumburg', 'Decatur'], near: ['Wisconsin', 'Indiana', 'Iowa', 'Missouri', 'Kentucky'] },
  { name: 'Indiana', code: 'IN', cities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel', 'Fishers', 'Bloomington', 'Hammond', 'Gary', 'Lafayette', 'Muncie', 'Noblesville', 'Terre Haute', 'Kokomo', 'Anderson', 'Greenwood'], near: ['Illinois', 'Michigan', 'Ohio', 'Kentucky'] },
  { name: 'Iowa', code: 'IA', cities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City', 'Ankeny', 'West Des Moines', 'Ames', 'Waterloo', 'Council Bluffs', 'Dubuque', 'Urbandale', 'Cedar Falls', 'Marion'], near: ['Minnesota', 'Wisconsin', 'Illinois', 'Missouri', 'Nebraska', 'South Dakota'] },
  { name: 'Kansas', code: 'KS', cities: ['Wichita', 'Overland Park', 'Kansas City', 'Olathe', 'Topeka', 'Lawrence', 'Shawnee', 'Lenexa', 'Manhattan', 'Salina', 'Hutchinson', 'Leavenworth', 'Leawood', 'Dodge City'], near: ['Nebraska', 'Missouri', 'Oklahoma', 'Colorado'] },
  { name: 'Kentucky', code: 'KY', cities: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington', 'Richmond', 'Georgetown', 'Florence', 'Hopkinsville', 'Nicholasville', 'Elizabethtown', 'Henderson', 'Frankfort', 'Paducah'], near: ['Indiana', 'Ohio', 'West Virginia', 'Virginia', 'Tennessee', 'Missouri', 'Illinois'] },
  { name: 'Louisiana', code: 'LA', cities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles', 'Kenner', 'Bossier City', 'Monroe', 'Alexandria', 'Houma', 'Metairie', 'Hammond', 'Slidell', 'Ruston'], near: ['Texas', 'Arkansas', 'Mississippi', 'Alabama'] },
  { name: 'Maine', code: 'ME', cities: ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn', 'Biddeford', 'Sanford', 'Saco', 'Westbrook', 'Augusta', 'Waterville', 'Brunswick'], near: ['New Hampshire', 'Vermont', 'Massachusetts'] },
  { name: 'Maryland', code: 'MD', cities: ['Baltimore', 'Columbia', 'Germantown', 'Silver Spring', 'Frederick', 'Rockville', 'Gaithersburg', 'Bowie', 'Hagerstown', 'Annapolis', 'Waldorf', 'Salisbury', 'College Park', 'Ellicott City'], near: ['Pennsylvania', 'Delaware', 'Virginia', 'West Virginia'] },
  { name: 'Massachusetts', code: 'MA', cities: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell', 'Brockton', 'Quincy', 'Lynn', 'New Bedford', 'Fall River', 'Newton', 'Lawrence', 'Somerville', 'Framingham', 'Haverhill', 'Waltham'], near: ['New Hampshire', 'Vermont', 'New York', 'Connecticut', 'Rhode Island'] },
  { name: 'Michigan', code: 'MI', cities: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor', 'Lansing', 'Dearborn', 'Clinton Township', 'Canton', 'Livonia', 'Troy', 'Westland', 'Farmington Hills', 'Flint', 'Kalamazoo', 'Southfield'], near: ['Ohio', 'Indiana', 'Wisconsin'] },
  { name: 'Minnesota', code: 'MN', cities: ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington', 'Brooklyn Park', 'Plymouth', 'Woodbury', 'Maple Grove', 'St. Cloud', 'Eagan', 'Eden Prairie', 'Coon Rapids', 'Blaine', 'Lakeville', 'Burnsville'], near: ['Wisconsin', 'Iowa', 'South Dakota', 'North Dakota'] },
  { name: 'Mississippi', code: 'MS', cities: ['Jackson', 'Gulfport', 'Southaven', 'Biloxi', 'Hattiesburg', 'Olive Branch', 'Tupelo', 'Meridian', 'Greenville', 'Madison', 'Clinton', 'Pearl', 'Oxford', 'Starkville'], near: ['Alabama', 'Tennessee', 'Arkansas', 'Louisiana'] },
  { name: 'Missouri', code: 'MO', cities: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Independence', "Lee's Summit", "O'Fallon", 'St. Joseph', 'St. Charles', 'Blue Springs', 'Joplin', 'Chesterfield', 'Jefferson City', 'Cape Girardeau'], near: ['Iowa', 'Illinois', 'Kentucky', 'Tennessee', 'Arkansas', 'Oklahoma', 'Kansas', 'Nebraska'] },
  { name: 'Montana', code: 'MT', cities: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Butte', 'Helena', 'Kalispell', 'Havre', 'Anaconda', 'Miles City', 'Belgrade', 'Livingston'], near: ['Idaho', 'Wyoming', 'South Dakota', 'North Dakota'] },
  { name: 'Nebraska', code: 'NE', cities: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney', 'Fremont', 'Hastings', 'Norfolk', 'Columbus', 'North Platte', 'Papillion', 'La Vista', 'Scottsbluff', 'South Sioux City'], near: ['South Dakota', 'Iowa', 'Missouri', 'Kansas', 'Colorado', 'Wyoming'] },
  { name: 'Nevada', code: 'NV', cities: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks', 'Carson City', 'Fernley', 'Elko', 'Mesquite', 'Boulder City', 'Fallon', 'Winnemucca'], near: ['California', 'Oregon', 'Idaho', 'Utah', 'Arizona'] },
  { name: 'New Hampshire', code: 'NH', cities: ['Manchester', 'Nashua', 'Concord', 'Derry', 'Dover', 'Rochester', 'Salem', 'Merrimack', 'Hudson', 'Londonderry', 'Keene', 'Portsmouth'], near: ['Maine', 'Vermont', 'Massachusetts'] },
  { name: 'New Jersey', code: 'NJ', cities: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Lakewood', 'Edison', 'Woodbridge', 'Toms River', 'Hamilton', 'Trenton', 'Clifton', 'Camden', 'Brick', 'Cherry Hill', 'Passaic', 'Union City'], near: ['New York', 'Pennsylvania', 'Delaware'] },
  { name: 'New Mexico', code: 'NM', cities: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell', 'Farmington', 'Hobbs', 'Clovis', 'Carlsbad', 'Alamogordo', 'Gallup', 'Los Lunas'], near: ['Arizona', 'Colorado', 'Oklahoma', 'Texas', 'Utah'] },
  { name: 'New York', code: 'NY', cities: ['New York City', 'Buffalo', 'Yonkers', 'Rochester', 'Syracuse', 'Albany', 'New Rochelle', 'Mount Vernon', 'Schenectady', 'Utica', 'White Plains', 'Hempstead', 'Troy', 'Niagara Falls', 'Binghamton', 'Ithaca'], near: ['New Jersey', 'Pennsylvania', 'Connecticut', 'Massachusetts', 'Vermont'] },
  { name: 'North Carolina', code: 'NC', cities: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem', 'Fayetteville', 'Cary', 'Wilmington', 'High Point', 'Concord', 'Asheville', 'Greenville', 'Gastonia', 'Jacksonville', 'Chapel Hill', 'Apex'], near: ['Virginia', 'Tennessee', 'Georgia', 'South Carolina'] },
  { name: 'North Dakota', code: 'ND', cities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo', 'Williston', 'Dickinson', 'Mandan', 'Jamestown', 'Wahpeton', 'Devils Lake', 'Valley City'], near: ['Minnesota', 'South Dakota', 'Montana'] },
  { name: 'Ohio', code: 'OH', cities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton', 'Parma', 'Canton', 'Youngstown', 'Lorain', 'Hamilton', 'Springfield', 'Kettering', 'Elyria', 'Lakewood', 'Cuyahoga Falls'], near: ['Michigan', 'Pennsylvania', 'West Virginia', 'Kentucky', 'Indiana'] },
  { name: 'Oklahoma', code: 'OK', cities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond', 'Lawton', 'Moore', 'Midwest City', 'Enid', 'Stillwater', 'Owasso', 'Muskogee', 'Bartlesville', 'Shawnee'], near: ['Kansas', 'Missouri', 'Arkansas', 'Texas', 'New Mexico', 'Colorado'] },
  { name: 'Oregon', code: 'OR', cities: ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro', 'Beaverton', 'Bend', 'Medford', 'Springfield', 'Corvallis', 'Albany', 'Tigard', 'Lake Oswego', 'Grants Pass'], near: ['Washington', 'Idaho', 'Nevada', 'California'] },
  { name: 'Pennsylvania', code: 'PA', cities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Reading', 'Erie', 'Scranton', 'Bethlehem', 'Lancaster', 'Harrisburg', 'York', 'Altoona', 'Wilkes-Barre', 'State College', 'Chester', 'Easton', 'Norristown'], near: ['New York', 'New Jersey', 'Delaware', 'Maryland', 'West Virginia', 'Ohio'] },
  { name: 'Rhode Island', code: 'RI', cities: ['Providence', 'Warwick', 'Cranston', 'Pawtucket', 'East Providence', 'Woonsocket', 'Coventry', 'Cumberland', 'North Providence', 'South Kingstown', 'West Warwick', 'Johnston', 'Newport', 'Bristol'], near: ['Massachusetts', 'Connecticut', 'New York'] },
  { name: 'South Carolina', code: 'SC', cities: ['Charleston', 'Columbia', 'North Charleston', 'Mount Pleasant', 'Rock Hill', 'Greenville', 'Summerville', 'Goose Creek', 'Sumter', 'Hilton Head Island', 'Florence', 'Spartanburg', 'Myrtle Beach', 'Aiken', 'Anderson'], near: ['North Carolina', 'Georgia', 'Tennessee'] },
  { name: 'South Dakota', code: 'SD', cities: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown', 'Mitchell', 'Yankton', 'Pierre', 'Huron', 'Spearfish', 'Vermillion', 'Brandon'], near: ['North Dakota', 'Minnesota', 'Iowa', 'Nebraska', 'Wyoming', 'Montana'] },
  { name: 'Tennessee', code: 'TN', cities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville', 'Murfreesboro', 'Franklin', 'Jackson', 'Johnson City', 'Bartlett', 'Hendersonville', 'Kingsport', 'Collierville', 'Smyrna', 'Cleveland', 'Brentwood'], near: ['Kentucky', 'Virginia', 'North Carolina', 'Georgia', 'Alabama', 'Mississippi', 'Arkansas', 'Missouri'] },
  { name: 'Texas', code: 'TX', cities: ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi', 'Plano', 'Laredo', 'Lubbock', 'Irving', 'Garland', 'Frisco', 'McKinney', 'Amarillo'], near: ['Oklahoma', 'Arkansas', 'Louisiana', 'New Mexico'] },
  { name: 'Utah', code: 'UT', cities: ['Salt Lake City', 'West Valley City', 'West Jordan', 'Provo', 'St. George', 'Orem', 'Sandy', 'Ogden', 'Lehi', 'South Jordan', 'Layton', 'Logan', 'Millcreek', 'Herriman'], near: ['Idaho', 'Wyoming', 'Colorado', 'Arizona', 'Nevada'] },
  { name: 'Vermont', code: 'VT', cities: ['Burlington', 'South Burlington', 'Rutland', 'Essex Junction', 'Barre', 'Montpelier', 'Winooski', 'St. Albans', 'Newport', 'Vergennes', 'Middlebury', 'Brattleboro'], near: ['New Hampshire', 'Massachusetts', 'New York'] },
  { name: 'Virginia', code: 'VA', cities: ['Virginia Beach', 'Chesapeake', 'Norfolk', 'Richmond', 'Arlington', 'Newport News', 'Alexandria', 'Hampton', 'Roanoke', 'Portsmouth', 'Suffolk', 'Lynchburg', 'Harrisonburg', 'Charlottesville', 'Leesburg', 'Blacksburg'], near: ['Maryland', 'West Virginia', 'Kentucky', 'Tennessee', 'North Carolina'] },
  { name: 'Washington', code: 'WA', cities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue', 'Kent', 'Everett', 'Renton', 'Spokane Valley', 'Federal Way', 'Yakima', 'Kirkland', 'Bellingham', 'Auburn', 'Kennewick', 'Olympia'], near: ['Oregon', 'Idaho', 'Montana'] },
  { name: 'West Virginia', code: 'WV', cities: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling', 'Weirton', 'Fairmont', 'Martinsburg', 'Beckley', 'Clarksburg', 'South Charleston', 'St. Albans', 'Vienna', 'Bluefield'], near: ['Ohio', 'Pennsylvania', 'Maryland', 'Virginia', 'Kentucky'] },
  { name: 'Wisconsin', code: 'WI', cities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine', 'Appleton', 'Waukesha', 'Eau Claire', 'Oshkosh', 'Janesville', 'West Allis', 'La Crosse', 'Sheboygan', 'Wauwatosa', 'Fond du Lac', 'Wausau'], near: ['Minnesota', 'Michigan', 'Illinois', 'Iowa'] },
  { name: 'Wyoming', code: 'WY', cities: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs', 'Sheridan', 'Green River', 'Evanston', 'Riverton', 'Jackson', 'Cody', 'Rawlins'], near: ['Montana', 'South Dakota', 'Nebraska', 'Colorado', 'Utah', 'Idaho'] },
];

/** The state a URL slug names ("new-york"), or null. */
export const stateBySlug = (slug = '') => STATES.find((s) => stateSlug(s.name) === String(slug).toLowerCase()) || null;
